project_id = "nutlcbnruabjsxecqpnd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54324
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[[storage.buckets]]
name = "blog-images"
public = true

[[storage.buckets]]
name = "partner-logos"
public = true

[[storage.buckets]]
name = "ads-banners"
public = true

[[storage.buckets]]
name = "partners-logos"
public = true

[[storage.buckets]]
name = "testimonials"
public = true

[[storage.buckets]]
name = "highlights"
public = true

[functions.send-push-notification]
verify_jwt = false