-- Inserir dados de exemplo na tabela agenda_itens
INSERT INTO agenda_itens (
  title,
  subtitle,
  city,
  starts_at,
  end_at,
  cover_url,
  slug,
  status,
  highlight_type,
  summary,
  tags,
  ticket_url,
  location_name,
  created_at,
  updated_at
) VALUES 
(
  'Festival de Música Eletrônica Porto Alegre',
  'Uma noite inesquecível com os melhores DJs',
  'Porto Alegre',
  '2025-09-15T20:00:00Z',
  '2025-09-16T03:00:00Z',
  'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
  'festival-musica-eletronica-porto-alegre',
  'published',
  'vitrine',
  'O maior festival de música eletrônica do sul do Brasil retorna com uma lineup incrível.',
  ARRAY['eletrônica', 'festival', 'música'],
  'https://example.com/tickets',
  'Arena do Grêmio',
  NOW(),
  NOW()
),
(
  'Show de Rock Nacional - São Paulo',
  'Bandas locais se apresentam no centro da cidade',
  'São Paulo',
  '2025-09-12T19:30:00Z',
  '2025-09-12T23:00:00Z',
  'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800',
  'show-rock-nacional-sao-paulo',
  'published',
  'curadoria',
  'Uma noite especial com o melhor do rock nacional.',
  ARRAY['rock', 'nacional', 'show'],
  'https://example.com/tickets-rock',
  'Centro Cultural SP',
  NOW(),
  NOW()
),
(
  'Teatro Musical - Rio de Janeiro',
  'Espetáculo baseado em clássicos da MPB',
  'Rio de Janeiro',
  '2025-09-10T20:00:00Z',
  '2025-09-10T22:30:00Z',
  'https://images.unsplash.com/photo-1507676184-d5ba0095b089?w=800',
  'teatro-musical-rio-janeiro',
  'published',
  'curadoria',
  'Um espetáculo que celebra a música popular brasileira.',
  ARRAY['teatro', 'musical', 'mpb'],
  'https://example.com/tickets-teatro',
  'Teatro Municipal',
  NOW(),
  NOW()
),
(
  'Festival Gastronômico - Florianópolis',
  'Sabores da Ilha reunidos em um só lugar',
  'Florianópolis',
  '2025-09-20T12:00:00Z',
  '2025-09-20T22:00:00Z',
  'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
  'festival-gastronomico-florianopolis',
  'published',
  'vitrine',
  'O melhor da gastronomia catarinense em um evento único.',
  ARRAY['gastronomia', 'festival', 'culinária'],
  'https://example.com/tickets-gastro',
  'Mercado Público',
  NOW(),
  NOW()
),
(
  'Exposição de Arte Contemporânea - Curitiba',
  'Artistas locais expõem suas obras mais recentes',
  'Curitiba',
  '2025-09-08T10:00:00Z',
  '2025-10-08T18:00:00Z',
  'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800',
  'exposicao-arte-contemporanea-curitiba',
  'published',
  'curadoria',
  'Uma exposição que celebra a criatividade local.',
  ARRAY['arte', 'exposição', 'contemporânea'],
  NULL,
  'Museu Oscar Niemeyer',
  NOW(),
  NOW()
);