-- Add billing fields to organizers table
ALTER TABLE public.organizers 
ADD COLUMN IF NOT EXISTS invoice_name TEXT,
ADD COLUMN IF NOT EXISTS tax_id TEXT,
ADD COLUMN IF NOT EXISTS invoice_email TEXT,
ADD COLUMN IF NOT EXISTS pix_key TEXT,
ADD COLUMN IF NOT EXISTS bank JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS links JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS whatsapp TEXT,
ADD COLUMN IF NOT EXISTS avatar_url TEXT,
ADD COLUMN IF NOT EXISTS avatar_alt TEXT;