-- Insert some test data into entity_profiles
INSERT INTO public.entity_profiles (type, handle, name, city, state, country, bio_short, bio, avatar_url, cover_url, tags, verified) VALUES
('artista', 'joaomusico', 'João Silva', 'São Paulo', 'SP', 'BR', 'Músico independente focado em MPB e rock alternativo', 'João Silva é um músico paulistano que vem conquistando o cenário independente com suas composições autorais que misturam MPB e rock alternativo. Com mais de 10 anos de carreira, já se apresentou em diversos festivais e casas de show da capital.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800', ARRAY['mpb', 'rock', 'independente'], true),

('local', 'estudiosom', 'Estúdio Som & Arte', 'Rio de Janeiro', 'RJ', 'BR', 'Espaço cultural com foco em música autoral e experimental', 'O Estúdio Som & Arte é um espaço cultural localizado no coração do Rio de Janeiro, dedicado à promoção da música autoral e experimental. Com uma acústica excepcional e ambiente intimista, o local oferece shows, workshops e residências artísticas.', 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400', 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800', ARRAY['musica', 'cultural', 'shows'], false),

('organizador', 'festivalsul', 'Festival Sul Independente', 'Porto Alegre', 'RS', 'BR', 'Organização dedicada à promoção da cultura independente no Sul', 'O Festival Sul Independente é uma organização sem fins lucrativos que há 8 anos promove a cultura independente na região Sul do Brasil. Realizamos eventos, festivais e ações de fomento cultural, apoiando artistas locais e criando conexões entre diferentes manifestações artísticas.', 'https://images.unsplash.com/photo-1549451371-64aa98a6f632?w=400', 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800', ARRAY['festival', 'independente', 'cultural'], true),

('artista', 'mariapop', 'Maria Santos', 'Florianópolis', 'SC', 'BR', 'Cantora e compositora de pop alternativo', 'Maria Santos é uma artista catarinense que conquistou destaque no cenário pop alternativo nacional. Com sua voz marcante e letras autorais, explora temas como relacionamentos, ansiedade e empoderamento feminino.', 'https://images.unsplash.com/photo-1494790108755-2616b612b820?w=400', 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800', ARRAY['pop', 'alternativo', 'feminista'], false),

('local', 'barcultural', 'Bar Cultural Esquina', 'Curitiba', 'PR', 'BR', 'Bar com programação cultural diversificada', 'O Bar Cultural Esquina é um point da cena cultural curitibana, oferecendo uma programação diversificada que inclui shows de música autoral, saraus, debates e exposições. Um espaço de encontro para artistas e apreciadores da cultura independente.', 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=400', 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800', ARRAY['bar', 'cultural', 'shows'], true);